# Emotiv Headset Configuration
authentication:
  client_id: "your_client_id_here"
  client_secret: "your_client_secret_here"
  username: "your_username_here"
  password: "your_password_here"

headset:
  device_id: null  # null for auto-detection
  model: "EPOC_X"  # EPOC_X, FLEX, INSIGHT
  channels:
    eeg_channels: ["AF3", "F7", "F3", "FC5", "T7", "P7", "O1", "O2", "P8", "T8", "FC6", "F4", "F8", "AF4"]

streaming:
  eeg_rate: 256
  motion_rate: 32
  streams:
    eeg: true
    motion: false
    dev: false

quality:
  contact_quality:
    threshold: 2000
    check_interval: 5.0
