# EEG Processing Pipeline Configuration
eeg_processing:
  sampling_rate: 256
  window_length: 4.0
  overlap: 0.5
  filters:
    lowpass: 40.0
    highpass: 0.5
    notch: 60.0
  frequency_bands:
    delta: [0.5, 4.0]
    theta: [4.0, 8.0]
    alpha: [8.0, 12.0]
    beta: [12.0, 30.0]
    gamma: [30.0, 40.0]

model:
  architecture:
    n_channels: 14
    n_classes: 7
    sampling_rate: 256
    cnn_filters: [32, 64, 128]
    gcn_hidden: 128
    transformer_dim: 256
    transformer_heads: 8
    transformer_layers: 4
    dropout: 0.3
  save_path: "models/eeg_model.pth"
  scaler_path: "models/feature_scaler.pkl"

inference:
  confidence_threshold: 0.7
  prediction_smoothing: true
  smoothing_window: 5
