# Robot Control Configuration
movement:
  step_size: 0.01  # meters
  speed: 0.1      # m/s
  home_position: [0.0, 0.0, 0.3]
  smoothing:
    enabled: true
    factor: 0.7

safety:
  position_limits:
    - [-0.5, 0.5]  # X axis [min, max] in meters
    - [-0.5, 0.5]  # Y axis [min, max] in meters
    - [0.1, 0.8]   # Z axis [min, max] in meters
  velocity_limits: [0.2, 0.2, 0.2]  # max velocity [x, y, z] m/s
  max_acceleration: 1.0  # m/s²

control:
  confidence_threshold: 0.7

simulation:
  enabled: true
  output_file: "robot_commands.json"
